### ISSUE TITLE
Cannot get config.json right with Multiple Plugs or Accessories. 

### ISSUE THREAD

**Issue by warrendt** [suda/homebridge-platform-energenie#6]
Hi there, 

Please see my config.json, every time I try to add the energenie code to the HomeBridge configuration it breaks everything else. 
I also cannot add more than one plug, am I missing something when it comes to syntax ? 
Keeps saying its invalid 

root@raspberrypi:~/.homebridge# cat config.json 
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "accessories": [
        {
            "accessory": "Homebridge-Paradox",
            "name": "Alarm System",
            "mqttusername": "",
            "mqttpassword": "",
            "mqttserver": "mqtt://localhost",
            "controltopic": "Paradox/C/P1",
	        "statetopic": "Paradox/Events",
	        "stayevent": "Event:Non-reportable event;SubEvent:Arm in stay mode",
	        "armevent": "Event:Partition status;SubEvent:Arm partition",
	        "disarmevent": "Event:Partition status;SubEvent:Disarm partition",
	        "triggeredevent": ""
        }
    ]
   
"description": "",

   "platforms": [
       {
         "platform": "Energenie",
         "name": "Energenie Platform",
         "delay": 500,
         "switches": [
               {
                       "name" : "Christmas Tree",
                       "on": {
                               "command": "on",
                               "socket": 1
                       },
                       "off": {
                               "command": "off",
                               "socket": 1
                       }
               }
         ]
       }
   ]
}

root@raspberrypi:~/.homebridge# *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-11-9 11:09:06] Loaded plugin: homebridge-paradox-security-system
[2017-11-9 11:09:06] Registering accessory 'homebridge-paradox.Homebridge-Paradox'
[2017-11-9 11:09:06] ---
[2017-11-9 11:09:06] Loaded plugin: homebridge-platform-energenie
[2017-11-9 11:09:06] Registering platform 'homebridge-platform-energenie.Energenie'
[2017-11-9 11:09:06] ---
[2017-11-9 11:09:06] There was a problem reading your config.json file.
[2017-11-9 11:09:06] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2017-11-9 11:09:06] 
/usr/local/lib/node_modules/homebridge/lib/server.js:206
    throw err;
    ^

SyntaxError: Unexpected string in JSON at position 731
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:200:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by The-Benjamin-Leo** [comment]
I'm having similar issues, did you ever get it sorted?
